version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8000"  # Expose backend on port 8080 externally
    environment:
      - DJANGO_SETTINGS_MODULE=projectname.settings  # Update to kanban.settings
    volumes:
      - ./kanban:/app/kanban  # Mount the kanban project directory
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge
