# Generated by Django 4.2 on 2024-10-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_card_created_at_card_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.column'),
            preserve_default=False,
        ),
    ]
